<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9pBI4XD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9pBI4XD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9pBI4XD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9pBI4XD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9pBI4XD\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '9pBI4XD',
    'container.build_id' => '05fb497e',
    'container.build_time' => 1550669776,
), __DIR__.\DIRECTORY_SEPARATOR.'Container9pBI4XD');
